### PR TITLE
Move session_id() call later into the process for better compatibility.

### PR DESCRIPTION
**Pull request by joshkoenig**
This addressess some issues we saw with EDD and Give plugins (e.g. #10).

Would love some more people to field test this before we roll in to release.

### CODE REVIEW

**Comment by DevinWalker** [comment]
I'll be sending folks over here as I can to test this PR :+1:

**Comment by joshkoenig** [comment]
Talked to Devin at WCLAX today and he confirmed this fixed the issues with Give.

**Comment by DevinWalker** [comment]
Yup should be good.

**Comment by joshkoenig** [comment]
Will have this rolled out on wp.org/plugins shortly.

**Comment by sparoministries** [comment]
Hate to kick an old dog but, Has this been resolved? I am getting the same error with the give plugin. Is there a way to resolve it that I missed?

**Comment by DevinWalker** [comment]
@sparoministries is this the error you're receiving? 

``` Warning: session_start(): user session functions not defined in...```

We did release some changes to how Give handles sessions recently. I still have a Pantheon test environment so I can look into this.

**Comment by DevinWalker** [comment]
I just did some initial tests and it seems to be working for me on give 1.4.1 and pantheon session 0.5

**Comment by sparoministries** [comment]
Here is the error...

1	session_start()	/wp-content/plugins/give/includes/class-give-session.php:347
2	Give_Session->maybe_start_session()	:null
3	call_user_func_array(Array ([0] => Give_Session Object ([] => ,[] => 1,[] => 604800,[] => ),[1] => maybe_start_session), Array ([0] => ))	/wp-includes/plugin.php:525
4	do_action(init)	/wp-settings.php:393
5	unknown()	/wp-config.php:161
6	unknown()	/wp-load.php:37
7	unknown()	/wp-blog-header.php:13
8	unknown()	/index.php:17

Using give 1.4.1

Where do I find pantheon sessions?

**Comment by craigbertrand** [comment]
I was logged in as sparoministries. I am helping them set this up. I usually work with Drupal and Pantheon. Forgive the wordpress n00b questions.

**Comment by DevinWalker** [comment]
Hey @craigbertrand here: https://wordpress.org/plugins/wp-native-php-sessions/

**Comment by craigbertrand** [comment]
That did it :) Thanks.

**Comment by DevinWalker** [comment]
Great! Glad to help. If you like our plugin and support please consider rating it: https://wordpress.org/support/view/plugin-reviews/give

See ya!

**Comment by craigbertrand** [comment]
Well now that it is not a wsod I like it more :) Appreciate the help! I will rate it as soon as we get it set up.

**Pull request merged**
