### PR TITLE
Update Composer dependencies (2020-07-07)

### PR DESCRIPTION
**Pull request by danielbachhuber**
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 7 updates, 0 removals
  - Updating symfony/deprecation-contracts (v2.1.2 => v2.1.3): Loading from cache
  - Updating symfony/event-dispatcher-contracts (v2.1.2 => v2.1.3): Downloading (100%)
  - Updating symfony/service-contracts (v2.1.2 => v2.1.3): Loading from cache
  - Updating symfony/translation-contracts (v2.1.2 => v2.1.3): Downloading (100%)
  - Updating myclabs/deep-copy (1.9.5 => 1.10.1): Loading from cache
  - Updating phpdocumentor/reflection-common (2.1.0 => 2.2.0): Loading from cache
  - Updating phpdocumentor/type-resolver (1.2.0 => 1.3.0): Loading from cache
Writing lock file
Generating autoload files
```

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@sugaroverflow Could you ask if the build failure is a known issue?

image

**Comment by sugaroverflow** [comment]
@danielbachhuber we're looking into it 😬

**Comment by sugaroverflow** [comment]
@danielbachhuber, we're thinking the site has too many multidevs so @greg-1-anderson removed some. There's still a few that won't load on the dashboard (weird).

I'm going to re-run the build!

**Comment by greg-1-anderson** [comment]
The problem is that the dev site is 504'ing, so the created multidev comes up uninstalled, ergo the search and replace fails. Not sure why the dev site is broken.

**Comment by greg-1-anderson** [comment]
OK, the dev site is back, but it's uninitialized (empty database).

Please re-install WordPress on the dev site, and initialize as needed for your tests. After you do that, you should be able to successfully re-run the tests for this PR.

**Comment by danielbachhuber** [comment]
> The problem is that the dev site is 504'ing, so the created multidev comes up uninstalled, ergo the search and replace fails. Not sure why the dev site is broken.

Ah, good debugging — I should've caught that. I think the dev site was "broken" because the database needed to be upgraded. WP SAML Auth, WP Redis, and Pantheon Advanced Page Cache all had the same problem, and their builds have been failing intermittently for the last week too.

> Please re-install WordPress on the dev site, and initialize as needed for your tests. After you do that, you should be able to successfully re-run the tests for this PR.

Looks like it's now failing in the same intermittent fashion as the other repos:

image

I tried debugging this last week on Pantheon Advanced Page Cache but wasn't able to solve it: https://github.com/pantheon-systems/pantheon-advanced-page-cache/pull/153

Originally I thought the `sleep` and suppressed script output meant CircleCI was killing the process when it didn't see any output. However, lowering the `sleep` value and allowing script output for `wp core install` didn't reliably fix the issue.

Have you seen this issue elsewhere, by chance? Or, any ideas on what might be going on?

**Comment by greg-1-anderson** [comment]
I did nothing other than re-run the test, and it worked. Well, I ran it with ssh, and AFAIK there's no way to exit the ssh session and get a green test, so it came out red (failed) again -- but everything else worked.

**Comment by danielbachhuber** [comment]
@greg-1-anderson I'm not sure I follow... The problem is that the build fails intermittently. Sometimes it passes, and other times it fails.

**Comment by greg-1-anderson** [comment]
Ah. Well, I don't know about that, but the `sleep 10` is suspicious. You might try replacing that with `terminus 
build:workflow:wait` and see if it works better.

**Comment by danielbachhuber** [comment]
@greg-1-anderson Looks like `terminus build:workflow:wait` did the trick. Thanks!

**Pull request closed without merging**
