### PR TITLE
Add a safety check that restores `$wpdb` when it's missing

### LINKED ISSUE #103: Ensure `$wpdb` object is available when writing a session on `session_write_close`
There have been at least a few reports of fatal errors because `$wpdb` isn't available in our `session_write_close` callback. For instance:

> I’ve done some investigation on the incompatibilities. The biggest problem is that Bookly decides to wait until objects are destructed to persist anything to the session (See `Bookly\Lib\UserBookingData` and the `destruct` method). By that logic, and from what I have seen, the custom session handler is going to be already destroyed by the time the plugin tries to write data to the session.

From https://wordpress.org/support/topic/pantheon-wp-native-sessions-and-bookly/
#49 is also a past thread.

We should identify some solution for this.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #103

### CODE REVIEW

**Comment by carl-alberto** [comment]
Hi @danielbachhuber! Any target date on when will the v 0.7.0 released along with this fix?

**Comment by danielbachhuber** [comment]
@carl-alberto I'll take care of it sometime this week, thanks!

**Comment by danielbachhuber** [comment]
@carl-alberto [v0.7.0 is now released](https://github.com/pantheon-systems/wp-native-php-sessions/releases/tag/v0.7.0), thanks for your patience.

**Comment by mattkenchington** [comment]
@danielbachhuber Thanks!  Does this mean that the Bookly plugin should now work on Pantheon?

**Comment by danielbachhuber** [comment]
@marktheunissen Not sure — I haven't tested personally. Feel free to open a new issue with reproduction steps and a suggested fix if possible.

**Pull request merged**
