### PR TITLE
Introduce static analysis

### PR DESCRIPTION
**Pull request by szepeviktor**
and :) fix errors

Start: `vendor/bin/phpstan analyze`

### CODE REVIEW

**Comment by szepeviktor** [comment]
@danielbachhuber Is it OK?

**Comment by szepeviktor** [comment]
Oh! is_countable() need to be removed from the WP stub: vendor/giacocorsiglia/wordpress-stubs/wordpress-stubs.php:73530 It is an ongoing issue.

**Comment by danielbachhuber** [comment]
@szepeviktor Thanks for the pull request 😄 I think we'll pass on this for now; I'm not sure of the value this provides.

**Comment by szepeviktor** [comment]
@danielbachhuber Static analysis makes developers feel joy 🎉 or ask questions ❓

**Pull request closed without merging**
