### PR TITLE
update class-session.php

### PR DESCRIPTION
**Pull request by bilalhassan**
use of undefined constant, updated to server time

### CODE REVIEW

**Comment by joshkoenig** [comment]
Thanks for the PR. If we're going to change this, any reason we wouldn't use ```time()```? 

I worry that moving from a constant to a superglobal will trade one set of "undefineds" for another.

**Comment by bilalhassan** [comment]
yeah that makes sense @joshkoenig

**Comment by joshkoenig** [comment]
Do you mind testing that and updating this PR? I'll see if I can get @mikevanwinkle can test it on our end sometime this week.

**Comment by joshkoenig** [comment]
Actually, looking at the PHP docs, the ```$_SERVER['REQUEST_TIME']``` superglobal has been available since PHP 5.1.0:

http://php.net/manual/en/reserved.variables.server.php

So maybe this is a-ok to use. I'm actually kind of curious where the ```REQUEST_TIME``` constant comes from in the first place.

**Comment by bilalhassan** [comment]
I had updated the plugin on the 2 applications i'm building with $_SERVER['REQUEST_TIME'] and haven't had any issues. The PHP warning is gone. I figured when the developer made a typo or something

**Comment by mikevanwinkle** [comment]
Agreed about the constant, can say I've seen that used much. I suppose the superglobal is probably faster than using time() which apparently does a syscall. Would there ever be an instance where the superglobal isn't set? I suspect this is pretty safe so I'd tentatively say we should include it in the next release.

**Comment by joshkoenig** [comment]
Agreed, @mikevanwinkle let's include the superglobal in the next release.

**Pull request merged**
